# Menotomy Matters by Shane Curcuru
# Many thanks for the awesome Minimal Mistakes theme and Jekyll sitebuilder
title: Menotomy Matters
email: alist@shanecurcuru.org
description: &description "Making sense of Arlington town government, one source document or news story at a time."
author:
  name      : &scname "Shane Curcuru"
  avatar    : "/assets/images/gravatar.png"
  location  : "Arlington, MA"
  email     : "alist@shanecurcuru.org"
  twitter   : &scid "ShaneCurcuru"
  linkedin  : *scid
  github    : *scid
  bio       : "Long-time Arlington resident and open source volunteer."

social:
  type: # Person or Organization (defaults to Person)
  name: *scname # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/ShaneCurcuru"
    - "https://github.com/ShaneCurcuru"
    - "https://linkedin.com/in/ShaneCurcuru"

# Build, theme, style settings
repository: "shanecurcuru/menotomymatters"
branch: "master"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
minimal_mistakes_skin: default
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

analytics:
  provider: "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "UA-6070690-9"

google:
  search_engine_id: "008313295041711467873:f701rjbr93s"

footer:
  links:
    - label: "About"
      icon: "fa fa-fw fa-address-card"
      url: "/about/"
    - label: "Credits"
      icon: "fa fa-fw fa-hand-holding-heart"
      url: "/colophon/"
    - label: "Terms"
      icon: "fa fa-fw fa-gavel"
      url: "/terms/"

include:
  - _pages
  - _issues
  
# Collections - expose data via archive pages
collections:
  issues:
    output: true
    excerpt: "One-Stop-FAQs on Town Issues"
    label: "Issues For Our Town"
    permalink: /:collection/:path

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      related: true
  - scope:
      path: "_issues"
      type: issues
    values:
      layout: single
      share: true
      related: true
      sidebar:
        nav: "archive"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
